### ISSUE TITLE
This error comes from cuvid link conflicts. You should link

### ISSUE THREAD

**Issue by hrtv721** [cap-ntu/Video-to-Online-Platform#17]
GPU in use: Quadro M6000
RuntimeError: NvDecoder : cuvidCtxLockCreate(&m_ctxLock, cuContext) returned error -1282253296 at src/NvDecoder/NvDecoder.cpp:524

I  don't quite understand how to deal with the conflicts,if I need link, how to link?

I tried "make NV_VERSION=<your nvidia driver major version>", it didn't work.
and I searched the problem on web, but there's no solution.
It will be very grateful ,if you can tell me the steps to debug it.

**Comment by YuanmingLeee** [comment]
Can you check your NVIDIA driver version:
```
nvidia-smi
```
The GPU version of the decoder can only be compiled for nvidia driver >= 396. If your driver is lower than this version, you may try modify [this line](https://github.com/cap-ntu/Video-to-Online-Platform/blob/1f8a7738fae7604e9dfea16d90279f05aefcb6b0/hysia/core/HysiaDecode/Makefile#L19)
to
```makefile
ifndef NV_VERSION
```
and run
```
make
```

This might be caused by a bug from the makefile. Thank you for spotting 😄
